ClubRecruitmentPortal/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import include, path
from Portalapp import views


urlpatterns = [
    url(r'', include('Portalapp.urls')),

]

Portalapp/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


app_name = 'Portalapp'
urlpatterns = [

    path('', views.index, name='index'),
	path('guest/', views.guest, name='guest'),
	path('guest_ieee/', views.guest_ieee, name='guest_ieee'),
	path('guest_ie/', views.guest_ie, name='guest_ie'),
	path('guest_iet/', views.guest_iet, name='guest_iet'),
	path('guest_acm/', views.guest_acm, name='guest_acm'),
	path('guest_rotaract/', views.guest_rotaract, name='guest_rotaract'),
	path('guest_iste/', views.guest_iste, name='guest_iste'),
	path('ieee/', views.ieee, name='ieee'),
	path('acm/', views.acm, name='acm'),
	path('rotaract/', views.rotaract, name='rotaract'),
	path('iste/', views.iste, name='iste'),
	path('ie/', views.ie, name='ie'),
	path('iet/', views.iet, name='iet'),
	path('confirmation/', views.confirmation, name='confirmation'),
    path('Admin/', views.Admin, name='Admin'),
	path('adminsite_ieee/', views.adminsite_ieee, name='adminsite_ieee'),
	path('adminsite_ie/', views.adminsite_ie, name='adminsite_ie'),
	path('adminsite_iet/', views.adminsite_iet, name='adminsite_iet'),
	path('adminsite_acm/', views.adminsite_acm, name='adminsite_acm'),
	path('adminsite_rotaract/', views.adminsite_rotaract, name='adminsite_rotaract'),
	path('adminsite_iste/', views.adminsite_iste, name='adminsite_iste'),
	path('approval_ieee/', views.approval_ieee, name='approval_ieee'),
	path('approval_ie/', views.approval_ie, name='approval_ie'),
	path('approval_iet/', views.approval_iet, name='approval_iet'),
	path('approval_acm/', views.approval_acm, name='approval_acm'),
	path('approval_iste/', views.approval_iste, name='approval_iste'),
	path('approval_rotaract/', views.approval_rotaract, name='approval_rotaract'),

]

Portalapp/models.py
from django.db import models

# Create your models here.
class Clubinfo(models.Model):
	
	club_text = models.CharField(max_length=2000)
	club_name= models.CharField(max_length=100)
	image=models.CharField(max_length=200,blank=True)
	def __str__(self):
		return self.club_text
		
class form(models.Model):
    name = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    roll_number = models.CharField(max_length=100)  
    date = models.CharField(max_length=100)
    info = models.CharField(blank=True,max_length=1000)
    email= models.EmailField()
    phone= models.CharField(max_length=100)
    address= models.CharField(max_length=1000)
    club=models.CharField(max_length=100,null=True)
    approval=models.IntegerField(default=0)
class admin(models.Model):
    user_name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    club_name = models.CharField(max_length=100)
	
class form2(models.Model):
    approval=models.CharField(max_length=10)


    

Portalapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import models
from .models import Clubinfo,form,admin,form2

class ApplicationForm(forms.Form):
    name = forms.CharField(max_length=100)
    branch = forms.CharField(max_length=100)
    roll_number = forms.CharField(max_length=100)  
    date = forms.CharField(max_length=100)
    info = forms.CharField(required=False,max_length=1000)
    email= forms.EmailField()
    phone= forms.CharField(max_length=100)
    address= forms.CharField(max_length=1000)
    club=forms.CharField(max_length=100)
	
    def save(self):
        new_entry = form.objects.create(
            name = self.cleaned_data['name'],
		    branch = self.cleaned_data['branch'],
		    roll_number = self.cleaned_data['roll_number'],
	        date = self.cleaned_data['date'],
		    info = self.cleaned_data['info'],
		    email = self.cleaned_data['email'],
		    phone = self.cleaned_data['phone'],
		    address = self.cleaned_data['address'],
            club=self.cleaned_data['club'],
			)
        return new_entry
	
    def clean_name(self):
        name = self.cleaned_data['name']
        count=0
        for i in name:
            if i.isalpha()==False:
                count=count+1
        if count>0:
            raise ValidationError("Name can only contain alphabets")
        return name
	
    def clean_branch(self):
        branch = self.cleaned_data['branch']
        count=0
        for i in branch:
            if i.isalpha()==False:
                count=count+1
        if count>0:
            raise ValidationError("Branch can only contain alphabets")
        return branch
		
    def clean_roll_number(self):
        roll_number = self.cleaned_data['roll_number']
        count=0
        for i in roll_number:
            if i.isalnum()==False :
                count=count+1
        if count>0 or len(roll_number)==0:
            raise ValidationError("Roll number can only contain alphabets and numbers and it cannot be left empty")
        return roll_number
	
    def clean_date(self):
        date = self.cleaned_data['date']
        count=0
        for i in date:
            if i.isalpha()==True:
                count=count+1
        if count>0:
            raise ValidationError("Date cannot contain alphabets")
        return date
		
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        count=0
        for i in phone:
            if i.isnumeric()==False:
                count=count+1
        if count>0:
            raise ValidationError("Phone number can only contain numbers")
        return phone
	
	
class AdminForm(forms.Form):
    club_name = forms.CharField(max_length=100)
    user_name = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100) 

class GuestForm(forms.Form):
    club_name = forms.CharField(max_length=100)  
	
class form21(forms.Form):
    approval = forms.IntegerField()
	
    def save(self):
        new_entry = form2.objects.create(
            approval = self.cleaned_data['approval'],
        )
        return new_entry

Portalapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse
from django.template import loader

from .models import Clubinfo,form,admin,form2
from .forms import ApplicationForm,AdminForm,form21,GuestForm



def index(request):
    template = loader.get_template('Portalapp/index.html')
    context = {}
    return HttpResponse(template.render(context, request))

def ieee(request):
    club_name="IEEE"
    club_info = get_object_or_404(Clubinfo, pk=1).club_text
    image= get_object_or_404(Clubinfo, pk=1).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')
    else:
        f = ApplicationForm()
    
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def acm(request):
    club_name="ACM"
    club_info = get_object_or_404(Clubinfo, pk=2).club_text
    image= get_object_or_404(Clubinfo, pk=2).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')

    else:
        f = ApplicationForm()
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def rotaract(request):
    club_name="Rotaract"
    club_info = get_object_or_404(Clubinfo, pk=3).club_text
    image= get_object_or_404(Clubinfo, pk=3).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')

    else:
        f = ApplicationForm()
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def iste(request):
    club_name="ISTE"
    club_info = get_object_or_404(Clubinfo, pk=5).club_text
    image= get_object_or_404(Clubinfo, pk=5).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')

    else:
        f = ApplicationForm()
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def ie(request):
    club_name="IE"
    club_info = get_object_or_404(Clubinfo, pk=4).club_text
    image= get_object_or_404(Clubinfo, pk=4).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')

    else:
        f = ApplicationForm()
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def iet(request):
    club_name="IET"
    club_info = get_object_or_404(Clubinfo, pk=6).club_text
    image= get_object_or_404(Clubinfo, pk=6).image
    if request.POST:
        f = ApplicationForm(request.POST)
        if f.is_valid():
            entry = f.save()
            return redirect('Portalapp:confirmation')

    else:
        f = ApplicationForm()
    template = loader.get_template('Portalapp/sub/club.html')
    context = {'club':club_name,'Clubinformation':club_info,'form':f,'image_url':image,}
    return HttpResponse(template.render(context, request))
def confirmation(request):
    template = loader.get_template('Portalapp/sub/information.html')
    context = {}
    return HttpResponse(template.render(context, request))
def Admin(request):
    error=""
    if request.POST:
        f=AdminForm(request.POST)
        if f.is_valid():
            q= get_object_or_404(admin, club_name=f.cleaned_data['club_name'])
            if f.cleaned_data['user_name']==q.user_name :
                if f.cleaned_data['password']==q.password :
                    if f.cleaned_data['club_name']=="IEEE":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_ieee'))
                    elif f.cleaned_data['club_name']=="IET":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_iet'))
                    elif f.cleaned_data['club_name']=="IE":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_ie'))
                    elif f.cleaned_data['club_name']=="ACM":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_acm'))
                    elif f.cleaned_data['club_name']=="ROTARACT":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_rotaract'))
                    elif f.cleaned_data['club_name']=="ISTE":
                        return HttpResponseRedirect(reverse('Portalapp:adminsite_iste'))
                    
                else:
                    error="Password is incorrect"
                    template = loader.get_template('Portalapp/sub/admin.html')
                    context = {'error':error,'form':f,}
                    return HttpResponse(template.render(context, request))
            else:
                error="Username is incorrect"
                template = loader.get_template('Portalapp/sub/admin.html')
                context = {'error':error,'form':f,}
                return HttpResponse(template.render(context, request))
    else:
        f=AdminForm()
    template = loader.get_template('Portalapp/sub/admin.html')
    context = {'error':error,'form':f,}
    return HttpResponse(template.render(context, request))

def adminsite_ieee(request):
    template = loader.get_template('Portalapp/sub/adminsite.html')
    club_name="IEEE"
    names=form.objects.values_list('name', flat=True).filter(club=club_name,approval=False)
    branch=form.objects.values_list('branch', flat=True).filter(club=club_name,approval=False)
    roll_number=form.objects.values_list('roll_number', flat=True).filter(club=club_name,approval=False)
    date=form.objects.values_list('date', flat=True).filter(club=club_name,approval=False)
    info=form.objects.values_list('info', flat=True).filter(club=club_name,approval=False)
    email=form.objects.values_list('email', flat=True).filter(club=club_name,approval=False)
    phone=form.objects.values_list('phone', flat=True).filter(club=club_name,approval=False)
    approval=form.objects.values_list('approval', flat=True).filter(club=club_name,approval=False)
    names_n=form.objects.values_list('name', flat=True).filter(club=club_name,approval=True)
    branch_n=form.objects.values_list('branch', flat=True).filter(club=club_name,approval=True)
    roll_number_n=form.objects.values_list('roll_number', flat=True).filter(club=club_name,approval=True)
    date_n=form.objects.values_list('date', flat=True).filter(club=club_name,approval=True)
    info_n=form.objects.values_list('info', flat=True).filter(club=club_name,approval=True)
    email_n=form.objects.values_list('email', flat=True).filter(club=club_name,approval=True)
    phone_n=form.objects.values_list('phone', flat=True).filter(club=club_name,approval=True)
    
    if request.POST:
        l=request.POST.getlist('approval')
        for i in range(len(l)):
            a=form2(approval=l[i])
            a.save()
        return redirect('Portalapp:approval_ieee')

    context = {'club_name':club_name,'name':names,'branch':branch,'roll_number':roll_number,'date':date,'info':info,'email':email,'phone':phone,'approval':approval,'name_n':names_n,'branch_n':branch_n,'roll_number_n':roll_number_n,'date_n':date_n,'info_n':info_n,'email_n':email_n,'phone_n':phone_n,}
    return HttpResponse(template.render(context, request))
	
def adminsite_ie(request):
    template = loader.get_template('Portalapp/sub/adminsite.html')
    club_name="IE"
    names=form.objects.values_list('name', flat=True).filter(club=club_name,approval=False)
    branch=form.objects.values_list('branch', flat=True).filter(club=club_name,approval=False)
    roll_number=form.objects.values_list('roll_number', flat=True).filter(club=club_name,approval=False)
    date=form.objects.values_list('date', flat=True).filter(club=club_name,approval=False)
    info=form.objects.values_list('info', flat=True).filter(club=club_name,approval=False)
    email=form.objects.values_list('email', flat=True).filter(club=club_name,approval=False)
    phone=form.objects.values_list('phone', flat=True).filter(club=club_name,approval=False)
    approval=form.objects.values_list('approval', flat=True).filter(club=club_name,approval=False)
    names_n=form.objects.values_list('name', flat=True).filter(club=club_name,approval=True)
    branch_n=form.objects.values_list('branch', flat=True).filter(club=club_name,approval=True)
    roll_number_n=form.objects.values_list('roll_number', flat=True).filter(club=club_name,approval=True)
    date_n=form.objects.values_list('date', flat=True).filter(club=club_name,approval=True)
    info_n=form.objects.values_list('info', flat=True).filter(club=club_name,approval=True)
    email_n=form.objects.values_list('email', flat=True).filter(club=club_name,approval=True)
    phone_n=form.objects.values_list('phone', flat=True).filter(club=club_name,approval=True)
    
    if request.POST:
        l=request.POST.getlist('approval')
        for i in range(len(l)):
            a=form2(approval=l[i])
            a.save()
        return redirect('Portalapp:approval_ie')

Portalapp/templates/Portalapp/sub/club.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="background-color: black">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{club}} Club Recriutment</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'Portalapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'Portalapp/css/simple-sidebar.css' %}" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style>
input,textarea {
    width: 100%;
	padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
	border-radius: 8px;
}
label {
font-size: 150%;
color: #dee5ef;
}
input:focus {
    background-color: lightblue;
}
#one:hover {
background-color: lightblue;
}

.responsive {
    width: 17vw;
    max-width: 180px;
    height: auto;
}



* {
    box-sizing: border-box;
}

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid rgb(218, 215, 215);
    border-radius: 4px;
    resize: vertical;
}

label {
    padding: 12px 12px 12px 0;
    display: inline-block;
}

input[type=submit] {
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    float: right;
}


.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}

.col-25 {
    float: left;
    width: 25%;
    margin-top: 6px;
}

.col-75 {
    float: left;
    width: 70%;
    margin-top: 6px;
}

.row:after {
    content: "";
    display: table;
    clear: both;
}
@media screen and (max-width: 600px) {
    .col-25, .col-75, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}

</style>

</head>

<body >
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" id="listd">
                <li class="sidebar-brand">
                        <a href="{% url 'Portalapp:index' %}"id = "sidetitle">
                                NITK Club Recruitment
                            </a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:Admin' %}">Admin Log In</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:guest' %}">Guest Log In</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:ieee' %}">IEEE</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:acm' %}">ACM</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:rotaract' %}">Rotaract</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:iste' %}">ISTE</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:ie' %}">IE</a>
                </li>
                <li>
                    <a href ="{% url 'Portalapp:iet' %}">IET</a>
                </li>
                   
            </ul>
        </div>
		<div id="page-content-wrapper" >
            <div class="container-fluid">
			<!-- club information will go here -->
			
            <h1 id="headingtextclub"><img src="{{image_url}}" class="responsive" alt="Club logo" style="float:left;border-radius:50%;margin-right:40px"> {{club}}</h1>
            <br><br>
                <hr>
                <p id="detailpclub" >{{Clubinformation}}</p>
                <center><a href="#headingtext" class="btn btn-secondary" id="clubapply"><strong>APPLY</strong></a>	</center>
                <br>
                <center><a href="{% url 'Portalapp:guest' %}" class="btn btn-secondary" id="clubapply"><strong>Check for Approved Submissions</strong></a>	</center>


            </div>
			<hr>
					<!-- FORM STARTS HERE -->
		

                    <h5 id="headingtext" style="text-align:center;background-color:rgb(151, 2, 2)" ><strong>{{club}} Recruitment Form</strong></h5>
                    <div class="container-fluid"  style="background-color:#383a3d">
                    <div class="col-lg-12">
                    <div class="col-lg-3"><br><br><br><br>
                    <div style="background-color:#383a3d;color:red;font-size:140%">
                      
                      <b>{{ form.non_field_errors }}{{ form.name.errors }}{{ form.roll_number.errors }}{{ form.email.errors }}{{ form.phone.errors }}{{ form.branch.errors }}{{ form.address.errors }}{{ form.date.errors }}{{ form.info.errors }}</b></div>
                    </div>
                    <div class="col-lg-6">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    
                    <form action="" method="post">
                        {% csrf_token %}
                        <table id="tablecss">
                            <tr>
                                <th><label for="id_name">Name:</label></th>
                                <td>
                                    
                                    <input type="text" name="name" required maxlength="100" id="id_name" autofocus autocomplete="off" />
                                </td>
                            </tr>
							<tr>
                                <th><label for="id_club">Club:</label></th>
                                <td>
                                    
                                    <input type="text" name="club"  id="id_club"  autocomplete="off" value="{{club}}" readonly />
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_roll_number">Roll Number:</label></th>
                                <td>
                                    
                                    <input type="text" name="roll_number" required maxlength="100" id="id_roll_number" autocomplete="off"/>
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_email">Email:</label></th>
                                <td>
                                    
                                    <input type="email" name="email" required maxlength="100" id="id_email" autocomplete="off" />
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_phone">Phone Number:</label></th>
                                <td>
                                    
                                    <input type="text" name="phone" required maxlength="100" id="id_phone" autocomplete="off" />
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_phone">Branch:</label></th>
                                <td>
                                    
                                    <input type="text" name="branch" required maxlength="100" id="id_branch" autocomplete="off"/>
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_address">Address:</label></th>
                                <td>
                                    
                                    <input type="text" name="address" required maxlength="1000" id="id_address" autocomplete="off"/>
                                </td>
                            </tr>
                            <tr>
                                <th><label for="id_phone">Date of Birth:</label></th>
                                <td>
                                    
                                    <input type="date" name="date" required maxlength="100" id="id_date" autocomplete="off"/>
                                </td>
                            </tr>
                            <tr>
                            <tr>
                                <th><label for="id_info">Why do you want to join the club? [List your achievements and relevant details]</label></th>
                                <td>
                                    
                                    <textarea type="text" name="info" required maxlength="1000" id="id_info" autocomplete="off" height=250px></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><input type="submit" id="one" ></td>
                            </tr>
                        </table>
                    </form><br><br>
                        <center><a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">MENU</a>	</center>
                        
                    <br></div>
                        
                        
                        <div class="col-lg-3"></div><br>
                        </div>
                        </div><br>
                        </div>
                        
		



<!-- Bootstrap core JavaScript -->
    <script src="{%static 'Portalapp/vendor/jquery/jquery.min.js' %}" ></script>
    <script src="{% static 'Portalapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script></div>

</body>

</html>

Portalapp/templates/Portalapp/sub/information.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="background-color: black">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Confirmation</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'Portalapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'Portalapp/css/simple-sidebar.css' %}" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<body>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" id="listd">
                <li class="sidebar-brand">
                        <a href="{% url 'Portalapp:index' %}"id = "sidetitle">
                                NITK Club Recruitment
                            </a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:Admin' %}">Admin Log In</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:guest' %}">Guest Log In</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:ieee' %}">IEEE</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:acm' %}">ACM</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:rotaract' %}">Rotaract</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:iste' %}">ISTE</a>
                </li>
                <li>
                    <a href="{% url 'Portalapp:ie' %}">IE</a>
                </li>
                <li>
                    <a href ="{% url 'Portalapp:iet' %}">IET</a>
                </li>
                   
            </ul>
        </div>
		<div id="page-content-wrapper">
		<div class="container-fluid">
               <div id="mainhead"> <h1 id="headingtext"><strong></strong>Thanks for applying!</h1></div><br><br>
			   <div><center><a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">MENU</a>	</center></div>
				</div></div></div>
				<script src="{% static 'Portalapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Portalapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
		<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>